name: ghcr publish

on:
  schedule:
    # Run every Sunday 22:31 UTC
    - cron: '31 22 * * 0'
  push:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image base
        uses: docker/build-push-action@v2
        with:
          context: base
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/base:latest

      - name: Build and push Docker image devel
        uses: docker/build-push-action@v2
        with:
          context: devel
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/devel:latest

      - name: Build and push Docker image firefox
        uses: docker/build-push-action@v2
        with:
          context: firefox
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/firefox:latest

      - name: Build and push Docker image isolinux
        uses: docker/build-push-action@v2
        with:
          context: isolinux
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/isolinux:latest

      - name: Build and push Docker image ghidra
        uses: docker/build-push-action@v2
        with:
          context: ghidra
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/ghidra:latest
