name: ghcr publish

on:
  schedule:
    # Run every Sunday 22:31 UTC
    - cron: '31 22 * * 0'
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  VERSION: latest

jobs:
  build-base:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image base
        uses: docker/build-push-action@v3
        with:
          context: base
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/base:${{ env.VERSION }}

  build-isolinux:

    runs-on: ubuntu-latest
    needs: [build-base]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image isolinux
        uses: docker/build-push-action@v3
        with:
          context: isolinux
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/isolinux:${{ env.VERSION }}

  build-novnc:

    runs-on: ubuntu-latest
    needs: [build-base]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image novnc
        uses: docker/build-push-action@v3
        with:
          context: novnc
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/novnc:${{ env.VERSION }}

  build-devel:

    runs-on: ubuntu-latest
    needs: [build-base]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image devel
        uses: docker/build-push-action@v3
        with:
          context: devel
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/devel:${{ env.VERSION }}

  build-ghidra:
    runs-on: ubuntu-latest
    needs: [build-devel]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image ghidra
        uses: docker/build-push-action@v3
        with:
          context: ghidra
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/ghidra:${{ env.VERSION }}

  build-pico:
    runs-on: ubuntu-latest
    needs: [build-devel]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image pico
        uses: docker/build-push-action@v3
        with:
          context: pico
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/pico:${{ env.VERSION }}

  build-gtk3:

    runs-on: ubuntu-latest
    needs: [build-base]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image gtk3
        uses: docker/build-push-action@v3
        with:
          context: gtk3
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/gtk3:${{ env.VERSION }}

  build-browser-chrome:

    runs-on: ubuntu-latest
    needs: [build-gtk3]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image chrome
        uses: docker/build-push-action@v3
        with:
          context: chrome
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/chrome:${{ env.VERSION }}

  build-browser-edge:

    runs-on: ubuntu-latest
    needs: [build-gtk3]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image edge
        uses: docker/build-push-action@v3
        with:
          context: edge
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/edge:${{ env.VERSION }}

  build-browser-firefox:

    runs-on: ubuntu-latest
    needs: [build-gtk3]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image firefox
        uses: docker/build-push-action@v3
        with:
          context: firefox
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/firefox:${{ env.VERSION }}

  build-novnc-firefox:

    runs-on: ubuntu-latest
    needs: [build-novnc]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image novnc-firefox
        uses: docker/build-push-action@v3
        with:
          context: novnc-firefox
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/novnc-firefox:${{ env.VERSION }}
